import shieldNames from "../names/shieldNames";

// InternalId: Object of {Type, Internal ID}
export default {
  OLDWOODENSHIELD: shieldNames.WOODEN_SHIELD,
  OLDSHIELD: shieldNames.WOODEN_SHIELD,
  WOODENSHIELD: shieldNames.WOODEN_SHIELD,
  STARTSHIELD: shieldNames.WOODEN_SHIELD,

  FRONTLINESHIELD: shieldNames.FRONT_LINE_SHIELD,
  WARRIORSHIELD: shieldNames.FRONT_LINE_SHIELD,
  MELEESHIELD: shieldNames.FRONT_LINE_SHIELD,

  CUDGEL: shieldNames.CUDGEL,
  SHIELD: shieldNames.CUDGEL, // !!! -- OVERLOADED VALUE

  PUNISHMENT: shieldNames.PUNISHMENT,
  AREASHIELD: shieldNames.PUNISHMENT,

  KNOCKBACKSHIELD: shieldNames.KNOCKBACK_SHIELD,
  KNOCKSHIELD: shieldNames.KNOCKBACK_SHIELD,
  BUMPSHIELD: shieldNames.KNOCKBACK_SHIELD,

  RAMPART: shieldNames.RAMPART,

  ASSAULTSHIELD: shieldNames.ASSAULT_SHIELD,
  DASHSHIELD: shieldNames.ASSAULT_SHIELD,

  BLOODTHIRSTYSHIELD: shieldNames.BLOODTHIRSTY_SHIELD,
  BLOODSHIELD: shieldNames.BLOODTHIRSTY_SHIELD,

  GREEDSHIELD: shieldNames.GREED_SHIELD,
  MONEYSHIELD: shieldNames.GREED_SHIELD,

  SPIKEDSHIELD: shieldNames.SPIKED_SHIELD,
  SPIKESHIELD: shieldNames.SPIKED_SHIELD,

  PARRYSHIELD: shieldNames.PARRY_SHIELD,
  FORCESHIELD: shieldNames.FORCE_SHIELD,

  THUNDERSHIELD: shieldNames.THUNDER_SHIELD,
  LIGHTNINGSHIELD: shieldNames.THUNDER_SHIELD,

  ICESHIELD: shieldNames.ICE_SHIELD,
  FROSTSHIELD: shieldNames.ICE_SHIELD,
};
