import trapNames from "../names/trapNames";

// InternalId: Object of {Type, Internal ID}
export default {
  SINEWSLICER: trapNames.SINEW_SLICER,
  STANDARDTURRET: trapNames.SINEW_SLICER,

  WOLFTRAP: trapNames.WOLF_TRAP,
  BEARTRAP: trapNames.WOLF_TRAP,
  ROOTTRAP: trapNames.WOLF_TRAP,

  CROSSBOMATIC: trapNames.CROSSBOMATIC,
  DOUBLECROSSBOMATIC: trapNames.CROSSBOMATIC,
  HORIZONTALTURRET: trapNames.CROSSBOMATIC,

  HEAVYTURRET: trapNames.HEAVY_TURRET,

  BARNACLE: trapNames.BARNACLE,
  CEILTURRET: trapNames.BARNACLE,
  CEILINGTURRET: trapNames.BARNACLE,

  FLAMETHROWERTURRET: trapNames.FLAMETHROWER_TURRET,
  FIRETURRET: trapNames.FLAMETHROWER_TURRET,

  CLEAVER: trapNames.CLEAVER,
  GROUNDSAW: trapNames.CLEAVER,
  SAWTRAP: trapNames.CLEAVER,
  SAW: trapNames.CLEAVER,

  CRUSHER: trapNames.CRUSHER,

  DECOY: trapNames.DECOY,
  EXPLOSIVEDECOY: trapNames.DECOY,

  DOOR: trapNames.DOOR,
  EMERGENCYDOOR: trapNames.DOOR,
  PORTABLEDOOR: trapNames.DOOR,
};
