import powerNames from "../names/powerNames";

export default {
  DEATHORB: powerNames.DEATHORB,
  SLOWORB: powerNames.DEATHORB,

  TORNADO: powerNames.TORNADO,

  KNIFEDANCE: powerNames.KNIFEDANCE,
  KNIVESCIRCLE: powerNames.KNIFEDANCE,

  CORRUPTEDPOWER: powerNames.CORRUPTEDPOWER,
  DAMAGEBUFF: powerNames.CORRUPTEDPOWER,

  VAMPIRISM: powerNames.VAMPIRISM,
  LEECHBUFF: powerNames.VAMPIRISM,

  TONIC: powerNames.TONIC,
  EXTRAHEAL: powerNames.TONIC,

  GRAPPLINGHOOK: powerNames.GRAPPLINGHOOK,
  HOOK: powerNames.GRAPPLINGHOOK,

  PHASER: powerNames.PHASER,
  BACKBLINK: powerNames.PHASER,

  CORROSIVECLOUD: powerNames.CORROSIVECLOUD,
  TOXICCLOUD: powerNames.CORROSIVECLOUD,

  LACERATINGAURA: powerNames.LACERATINGAURA,
  DAMAGEAURA: powerNames.LACERATINGAURA,

  WAVEOFDENIAL: powerNames.WAVEOFDENIAL,
  SHOCKWAVE: powerNames.WAVEOFDENIAL,

  WINGSOFTHECROW: powerNames.WINGSOFTHECROW,
  WINGS: powerNames.WINGSOFTHECROW,

  OWL: powerNames.OWL,
  GREATOWLOFWAR: powerNames.OWL,

  OWLUP: powerNames.OWLUP,
  OWLANGRY: powerNames.OWLUP,
  ANGRYOWL: powerNames.OWLUP,
  GREATOWLOFWARUP: powerNames.OWLUP,

  LIGHTSPEED: powerNames.LIGHTSPEED,
  DASH: powerNames.LIGHTSPEED,

  LIGHTSPEEDBACK: powerNames.LIGHTSPEEDBACK,
  DASHBACK: powerNames.LIGHTSPEEDBACK,

  GIANTWHISTLE: powerNames.GIANTWHISTLE,
  WHISTLE: powerNames.GIANTWHISTLE,

  TELLURICSHOCK: powerNames.TELLURICSHOCK,
  SEISMICSTOMP: powerNames.TELLURICSHOCK,

  SYRINGE: powerNames.SYRINGE,
  COLLECTORSPIN: powerNames.SYRINGE,
  COLLECTORSSYRINGE: powerNames.SYRINGE,
  COLLECTORSYRINGE: powerNames.SYRINGE,
  SPINTOWIN: powerNames.SYRINGE,
  BEYBLADE: powerNames.SYRINGE,

  SMOKEBOMB: powerNames.SMOKEBOMB,

  MUSHROOMBOI: powerNames.MUSHROOMBOI,
  SPAWNFRIENDLYHARDY: powerNames.MUSHROOMBOI,
  MUSHIEBOI: powerNames.MUSHROOMBOI,
  MUSHBOI: powerNames.MUSHROOMBOI,

  MUSHROOMBOIEXPLODE: powerNames.MUSHROOMBOIEXPLODE,
  EXPLODEFRIENDLYHARDY: powerNames.MUSHROOMBOIEXPLODE,
  EXPLODEMUSHIEBOI: powerNames.MUSHROOMBOI,
  EXPLODEMUSHBOI: powerNames.MUSHROOMBOI,

  LIGHTNINGRODS: powerNames.LIGHTNINGRODS,
  LIGHTNINGROD: powerNames.LIGHTNINGRODS,

  SCARECROWSSICKLES: powerNames.SCARECROWSSICKLES,
  GARDENERSICKLES: powerNames.SCARECROWSSICKLES,

  ICEARMOR: powerNames.ICEARMOR,

  SERENADE: powerNames.SERENADE,
  SERENADEPET: powerNames.SERENADE,
  FLYINGSWORD: powerNames.SERENADE,
  FLYINGSWORDPET: powerNames.SERENADE,

  COCOON: powerNames.COCOON,
  BUBBLESHIELDPOWER: powerNames.COCOON,
  BUBBLESHIELD: powerNames.COCOON,
};
