import grenadeNames from "../names/grenadeNames";

// InternalId: Object of {Type, Internal ID}
export default {
  INFANTRYGRENADE: grenadeNames.INFANTRY_GRENADE,
  FASTGRENADE: grenadeNames.INFANTRY_GRENADE,

  ICEGRENADE: grenadeNames.ICE_GRENADE,
  ICEBOMB: grenadeNames.ICE_GRENADE,

  POWERFULGRENADE: grenadeNames.POWERFUL_GRENADE,
  POWERFULBOMB: grenadeNames.POWERFUL_GRENADE,
  EXPLOSIVEGRENADE: grenadeNames.POWERFUL_GRENADE,

  CLUSTERGRENADE: grenadeNames.CLUSTER_GRENADE,
  CLUSTERBOMB: grenadeNames.CLUSTER_GRENADE,

  FIREGRENADE: grenadeNames.FIRE_GRENADE,
  FIREBOMB: grenadeNames.FIRE_GRENADE,

  MAGNETICGRENADE: grenadeNames.MAGNETIC_GRENADE,
  MAGNETGRENADE: grenadeNames.MAGNETIC_GRENADE,

  STUNGRENADE: grenadeNames.STUN_GRENADE,
  STUNBOMB: grenadeNames.STUN_GRENADE,

  ROOTGRENADE: grenadeNames.ROOT_GRENADE,
  ROOTBOMB: grenadeNames.ROOT_GRENADE,

  OILGRENADE: grenadeNames.OIL_GRENADE,
  OILBOMB: grenadeNames.OIL_GRENADE,

  SWARM: grenadeNames.SWARM,

  HUNTERSGRENADE: grenadeNames.HUNTERS_GRENADE,
};
