import enemyNames from "../names/enemyNames";

// InternalId: Object of {Type, Internal ID}
export default {
  ZOMBIE: enemyNames.ZOMBIE,

  ARCHER: enemyNames.ARCHER,
  UNDEADARCHER: enemyNames.ARCHER,

  WALLWORM: enemyNames.S_WALLEGGWORM,
  WALLEGGWORM: enemyNames.S_WALLEGGWORM,
  EGGWORM: enemyNames.S_WALLEGGWORM,
  SWAMPWORM: enemyNames.S_WALLEGGWORM,
  WEAVERWORM: enemyNames.S_WALLEGGWORM,

  SHIELDBEARER: enemyNames.SHIELDBEARER,
  SHIELD: enemyNames.SHIELDBEARER, // !!! -- OVERLOADED VALUE

  GRENADIER: enemyNames.GRENADIER,

  BOMBARDIER: enemyNames.BOMBARDIER,

  BAT: enemyNames.BAT,
  DASHBAT: enemyNames.BAT,

  KAMIKAZE: enemyNames.KAMIKAZE,

  RUNNER: enemyNames.RUNNER,

  INQUISITOR: enemyNames.INQUISITOR,
  MAGE360: enemyNames.INQUISITOR,

  PROTECTOR: enemyNames.PROTECTOR,

  HAMMER: enemyNames.HAMMER,

  FLY: enemyNames.S_FLY,
  HFLY: enemyNames.S_FLY,
  HAMMERFLY: enemyNames.S_FLY,
  DEPTHSFLY: enemyNames.S_FLY,

  SWEEPER: enemyNames.SWEEPER,
  MINIMOTH: enemyNames.SWEEPER,

  BUZZCUTTER: enemyNames.BUZZCUTTER,

  PURULENTZOMBIESEWER: enemyNames.PURULENT_ZOMBIE_S,
  SEWERZOMBIE: enemyNames.PURULENT_ZOMBIE_S,
  STILTZOMBIE: enemyNames.PURULENT_ZOMBIE_S,
  WORMZOMBIE: enemyNames.PURULENT_ZOMBIE_S,

  WORM: enemyNames.S_WORM,
  CORPSEWORM: enemyNames.S_WORM,
  ZOMBIEWORM: enemyNames.S_WORM,
  TRASHWORM: enemyNames.S_WORM,
  PURULENTWORM: enemyNames.S_WORM,

  PURULENTZOMBIEGRAVEYARD: enemyNames.PURULENT_ZOMBIE_G,
  GRAVEYARDZOMBIE: enemyNames.PURULENT_ZOMBIE_G,
  CEMETARYZOMBIE: enemyNames.PURULENT_ZOMBIE_G,
  FLYZOMBIE: enemyNames.PURULENT_ZOMBIE_G,

  ZOMBIEFLY: enemyNames.S_ZOMBIEFLY,
  CORPSEFLY: enemyNames.S_ZOMBIEFLY,
  ZFLY: enemyNames.S_ZOMBIEFLY,
  PURULENTFLY: enemyNames.S_ZOMBIEFLY,

  DISGUSTINGWORM: enemyNames.DISGUSTING_WORM,
  SEWERWORM: enemyNames.DISGUSTING_WORM,

  SCORPION: enemyNames.SCORPION,

  IMPALER: enemyNames.IMPALER,
  SPIKER: enemyNames.IMPALER,

  SEWERTENTACLE: enemyNames.SEWER_TTCL,
  SEWERTTCL: enemyNames.SEWER_TTCL,

  CATCHER: enemyNames.CATCHER,
  HOOKER: enemyNames.CATCHER,

  CLEAVER: enemyNames.CLEAVER,
  AXETHROWER: enemyNames.CLEAVER,

  PIRATECAPTAIN: enemyNames.PIRATE_CAPTAIN,
  PIRATE: enemyNames.PIRATE_CAPTAIN,

  KNIFETHROWER: enemyNames.KNIFE_THROWER,
  KUNAI: enemyNames.KNIFE_THROWER,
  KUNAITHROWER: enemyNames.KNIFE_THROWER,

  SLASHER: enemyNames.SLASHER,

  LACERATOR: enemyNames.LACERATOR,
  SPINNER: enemyNames.LACERATOR,

  SHOCKER: enemyNames.SHOCKER,

  THORNY: enemyNames.THORNY,

  SPAWNER: enemyNames.SPAWNER,

  MASKER: enemyNames.MASKER,
  FOGGER: enemyNames.MASKER,

  CASTER: enemyNames.CASTER,

  GOLEM: enemyNames.GOLEM,

  DARKTRACKER: enemyNames.DARK_TRACKER,
  NINJA: enemyNames.DARK_TRACKER,

  CANNIBAL: enemyNames.CANNIBAL,

  AUTOMATON: enemyNames.AUTOMATON,
  TIMEKEEPERBOT: enemyNames.AUTOMATON,

  LANCER: enemyNames.LANCER,

  GUARDIANKNIGHT: enemyNames.GUARDIAN_KNIGHT,

  ROYALGUARD: enemyNames.ROYAL_GUARD,
  FINGEROFTHEKING: enemyNames.ROYAL_GUARD,
  KINGSFINGER: enemyNames.ROYAL_GUARD,

  BOMBER: enemyNames.BOMBER,

  SLAMMER: enemyNames.SLAMMER,
  BIRD: enemyNames.SLAMMER,

  DEMON: enemyNames.DEMON,

  ARBITER: enemyNames.ARBITER,

  GROUNDSHAKER: enemyNames.GROUND_SHAKER,

  SKELETON: enemyNames.SKELETON,
  BIGBOOTS: enemyNames.SKELETON,

  RAMPAGER: enemyNames.RAMPAGER,

  FAILEDEXPERIMENT: enemyNames.FAILED_EXP,
  EXPERIMENT: enemyNames.FAILED_EXP,
  FAILED: enemyNames.FAILED_EXP,

  DEFENDER: enemyNames.DEFENDER,

  MAGISTRATE: enemyNames.MAGISTRATE,
  MAGISTRATEOFDEATH: enemyNames.MAGISTRATE,

  LIBRARIAN: enemyNames.LIBRARIAN,

  // ------------------------------ BAD SEED -------------------------------- //
  YEETER: enemyNames.YEETER,
  PITCHER: enemyNames.YEETER,

  JERKSHROOM: enemyNames.JERKSHROOM,
  MUSHROOM: enemyNames.JERKSHROOM,

  BANISHED: enemyNames.BANISHED,

  BLOWGUNNER: enemyNames.BLOWGUNNER,

  TICK: enemyNames.TICK,
  GIANTTICK: enemyNames.TICK,

  // --------------------------- BESTIARY UPDATE ---------------------------- //
  RAT: enemyNames.RAT,
  RANCIDRAT: enemyNames.RAT,

  OVENKNIGHT: enemyNames.OVEN_KNIGHT,
  GUARDIAN: enemyNames.OVEN_KNIGHT,
  SHIELDKNIGHT: enemyNames.OVEN_KNIGHT,
  ENFORCER: enemyNames.OVEN_KNIGHT,
  FURNACEKNIGHT: enemyNames.OVEN_KNIGHT,

  BLOBBY: enemyNames.BLOBBY,
  BLOB: enemyNames.BLOBBY,
  TOXICMIASMA: enemyNames.BLOBBY,

  CRAB: enemyNames.CRAB,
  SAMURAI: enemyNames.CRAB,
  WEIRDEDWARRIOR: enemyNames.CRAB,

  FATZOMBIE: enemyNames.FAT_ZOMBIE,
  CORPULENTZOMBIE: enemyNames.FAT_ZOMBIE,
  MUMMY: enemyNames.FAT_ZOMBIE,

  DUELIST: enemyNames.DUELIST,
  DANCER: enemyNames.DUELIST,

  // ------------------------ BARRELS O' FUN UPDATE ------------------------- //
  INFECTEDWORKER: enemyNames.INFECTED_WORKER,
  HURLER: enemyNames.INFECTED_WORKER,

  LIVINGBARREL: enemyNames.LIVING_BARREL,
  BARREL: enemyNames.LIVING_BARREL,
  MIMIC: enemyNames.LIVING_BARREL,

  // --------------------------- CHRISTMAS UPDATE --------------------------- //
  CROSSBOWMAN: enemyNames.CROSSBOW_MAN,
  DEMOLISHER: enemyNames.CROSSBOW_MAN,
  BOMBARCHER: enemyNames.CROSSBOW_MAN,

  // ----------------------------- FATAL FALLS ------------------------------ //
  CROW: enemyNames.CROW,
  ANNOYINGCROW: enemyNames.CROW,
  MYOPICCROW: enemyNames.CROW,
  FLYINGCROW: enemyNames.CROW,

  JAVELINSNAKE: enemyNames.JAVELIN_SNAKE,
  SNAKE: enemyNames.JAVELIN_SNAKE,
  COLDBLOODED: enemyNames.JAVELIN_SNAKE,
  COLDBLOODEDGUARDIAN: enemyNames.JAVELIN_SNAKE,

  AXESTATUE: enemyNames.AXE_STATUE,
  STATUEAXE: enemyNames.AXE_STATUE,
  STONEWARDENAXE: enemyNames.AXE_STATUE,
  AXESTONEWARDEN: enemyNames.AXE_STATUE,
  AXEWARDEN: enemyNames.AXE_STATUE,
  WARDENAXE: enemyNames.AXE_STATUE,

  SPEARSTATUE: enemyNames.SPEAR_STATUE,
  STATUESPEAR: enemyNames.SPEAR_STATUE,
  STONEWARDENSPEAR: enemyNames.SPEAR_STATUE,
  SPEARSTONEWARDEN: enemyNames.SPEAR_STATUE,
  SPEARWARDEN: enemyNames.SPEAR_STATUE,
  WARDENSPEAR: enemyNames.SPEAR_STATUE,

  NECROMANCER: enemyNames.NECROMANCER,
  NECRO: enemyNames.NECROMANCER,
  APOSTATE: enemyNames.NECROMANCER,
  NECROMANT: enemyNames.NECROMANCER,

  BOOTLEGHOMUNCULUS: enemyNames.BOOTLEG_BLOB,
  BOOTLEGHOMUN: enemyNames.BOOTLEG_BLOB,
  DEFAULTHOMUNCULUS: enemyNames.BOOTLEG_BLOB,
  BOOTLEGBLOB: enemyNames.BOOTLEG_BLOB,

  BOOTLEGBOWHOMUNCULUS: enemyNames.BOOTLEG_BOW,
  BOOTLEGBOWBLOB: enemyNames.BOOTLEG_BOW,
  BOOTLEGHOMUNCULUSBOW: enemyNames.BOOTLEG_BOW,
  BOOTLEGHOMUNBOW: enemyNames.BOOTLEG_BOW,
  BOOTLEGBOWMAN: enemyNames.BOOTLEG_BOW,
  BOOTLEGBOW: enemyNames.BOOTLEG_BOW,

  BOOTLEGSWORDHOMUNCULUS: enemyNames.BOOTLEG_SWORD,
  BOOTLEGSWORDBLOB: enemyNames.BOOTLEG_SWORD,
  BOOTLEGHOMUNCULUSSWORD: enemyNames.BOOTLEG_SWORD,
  BOOTLEGHOMUNSWORD: enemyNames.BOOTLEG_SWORD,
  BOOTLEGSWORDSMAN: enemyNames.BOOTLEG_SWORD,
  BOOTLEGSWORDMAN: enemyNames.BOOTLEG_SWORD,
  BOOTLEGSWORD: enemyNames.BOOTLEG_SWORD,

  BOOTLEGSHOVELHOMUNCULUS: enemyNames.BOOTLEG_SHOVEL,
  BOOTLEGSHOVELBLOB: enemyNames.BOOTLEG_SHOVEL,
  BOOTLEGHOMUNCULUSSHOVEL: enemyNames.BOOTLEG_SHOVEL,
  BOOTLEGHOMUNSHOVEL: enemyNames.BOOTLEG_SHOVEL,
  BOOTLEGSHOVELMAN: enemyNames.BOOTLEG_SHOVEL,
  BOOTLEGSHOVEL: enemyNames.BOOTLEG_SHOVEL,

  // ---------------------------------------------------------------------------
  // BOSSES
  // ---------------------------------------------------------------------------
  CONCIERGE: enemyNames.CONCIERGE,
  BEHEMOTH: enemyNames.CONCIERGE,

  CONJUNCTIVIUS: enemyNames.CONJU,
  CONJUNC: enemyNames.CONJU,
  CONJ: enemyNames.CONJU,
  CONJUNCT: enemyNames.CONJU,
  CONJONCTIVIUS: enemyNames.CONJU,

  MAMATICK: enemyNames.MAMA_TICK,

  TIMEKEEPER: enemyNames.TIME_KEEPER,

  GIANT: enemyNames.GIANT,

  HOTK: enemyNames.HOTK,
  HANDOFTHEKING: enemyNames.HOTK,
  HAND: enemyNames.HOTK,
  KINGSHAND: enemyNames.HOTK,

  COLLECTOR: enemyNames.COLLECTOR,

  SCARECROW: enemyNames.SCARECROW,
  GARDENER: enemyNames.SCARECROW,
  ROYALGARDENER: enemyNames.SCARECROW,
  THESCARECROW: enemyNames.SCARECROW,
  THEGARDENER: enemyNames.SCARECROW,
};
