import powerNames from "../names/powerNames";

export default {
  DEATHORB: powerNames.DEATH_ORB,
  SLOWORB: powerNames.DEATH_ORB,

  TORNADO: powerNames.TORNADO,

  KNIFEDANCE: powerNames.KNIFE_DANCE,
  KNIVESCIRCLE: powerNames.KNIFE_DANCE,

  CORRUPTEDPOWER: powerNames.CORRUPTED_POWER,
  DAMAGEBUFF: powerNames.CORRUPTED_POWER,

  VAMPIRISM: powerNames.VAMPIRISM,
  LEECHBUFF: powerNames.VAMPIRISM,

  TONIC: powerNames.TONIC,
  EXTRAHEAL: powerNames.TONIC,

  GRAPPLINGHOOK: powerNames.GRAPPLING_HOOK,
  HOOK: powerNames.GRAPPLING_HOOK,

  PHASER: powerNames.PHASER,
  BACKBLINK: powerNames.PHASER,

  CORROSIVECLOUD: powerNames.CORROSIVE_CLOUD,
  TOXICCLOUD: powerNames.CORROSIVE_CLOUD,

  LACERATINGAURA: powerNames.LACERATING_AURA,
  DAMAGEAURA: powerNames.LACERATING_AURA,

  WAVEOFDENIAL: powerNames.WAVE_OF_DENIAL,
  SHOCKWAVE: powerNames.WAVE_OF_DENIAL,

  WINGSOFTHECROW: powerNames.WINGS_OF_THE_CROW,
  WINGS: powerNames.WINGS_OF_THE_CROW,

  OWL: powerNames.OWL,
  GREATOWLOFWAR: powerNames.OWL,

  OWLUP: powerNames.OWL_UP,
  OWLANGRY: powerNames.OWL_UP,
  ANGRYOWL: powerNames.OWL_UP,
  GREATOWLOFWARUP: powerNames.OWL_UP,

  LIGHTSPEED: powerNames.LIGHTSPEED,
  DASH: powerNames.LIGHTSPEED,

  LIGHTSPEEDBACK: powerNames.LIGHTSPEED_BACK,
  DASHBACK: powerNames.LIGHTSPEED_BACK,

  GIANTWHISTLE: powerNames.GIANT_WHISTLE,
  WHISTLE: powerNames.GIANT_WHISTLE,

  TELLURICSHOCK: powerNames.TELLURIC_SHOCK,
  SEISMICSTOMP: powerNames.TELLURIC_SHOCK,

  SYRINGE: powerNames.SYRINGE,
  COLLECTORSPIN: powerNames.SYRINGE,
  COLLECTORSSYRINGE: powerNames.SYRINGE,
  COLLECTORSYRINGE: powerNames.SYRINGE,
  SPINTOWIN: powerNames.SYRINGE,
  BEYBLADE: powerNames.SYRINGE,

  SMOKEBOMB: powerNames.SMOKE_BOMB,

  MUSHROOMBOI: powerNames.MUSHROOM_BOI,
  SPAWNFRIENDLYHARDY: powerNames.MUSHROOM_BOI,
  MUSHIEBOI: powerNames.MUSHROOM_BOI,
  MUSHBOI: powerNames.MUSHROOM_BOI,

  MUSHROOMBOIEXPLODE: powerNames.MUSHROOM_BOI_EXPLODE,
  EXPLODEFRIENDLYHARDY: powerNames.MUSHROOM_BOI_EXPLODE,
  EXPLODEMUSHIEBOI: powerNames.MUSHROOM_BOI_EXPLODE,
  EXPLODEMUSHBOI: powerNames.MUSHROOM_BOI_EXPLODE,

  LIGHTNINGRODS: powerNames.LIGHTNING_RODS,
  LIGHTNINGROD: powerNames.LIGHTNING_RODS,

  SCARECROWSSICKLES: powerNames.SCARECROWS_SICKLES,
  GARDENERSICKLES: powerNames.SCARECROWS_SICKLES,

  ICEARMOR: powerNames.ICE_ARMOR,

  SERENADE: powerNames.SERENADE,
  SERENADEPET: powerNames.SERENADE,
  FLYINGSWORD: powerNames.SERENADE,
  FLYINGSWORDPET: powerNames.SERENADE,

  COCOON: powerNames.COCOON,
  BUBBLESHIELDPOWER: powerNames.COCOON,
  BUBBLESHIELD: powerNames.COCOON,

  // -------------------------- EVERYONE IS HERE ---------------------------- //
  FACEFLASK: powerNames.FACE_FLASK,
  FLASK: powerNames.FACE_FLASK,

  POLLOPOWER: powerNames.POLLO_POWER,
  CHICKENPOWER: powerNames.POLLO_POWER,
  CHICKEN: powerNames.POLLO_POWER,
  GUACAMELEEPOWER: powerNames.POLLO_POWER,

  // ------------------------- QUEEN AND THE SEA ---------------------------- //
  LEGHUGGER: powerNames.LEGHUGGER,
  LILSTAPHY: powerNames.LEGHUGGER,

  ADULTLEGHUGGER: powerNames.ADULT_LEGHUGGER,
  LEGHUGGERADULT: powerNames.ADULT_LEGHUGGER,
  LEGHUGGEREVOLVED: powerNames.ADULT_LEGHUGGER,
  EVOLVEDLEGHUGGER: powerNames.ADULT_LEGHUGGER,
  ADULTLILSTAPHY: powerNames.ADULT_LEGHUGGER,
  ADULTSTAPHY: powerNames.ADULT_LEGHUGGER,
};
