import enemyNames from "../names/enemyIds";

export default {
  ZOMBIE: enemyNames.ZOMBIE,

  ARCHER: enemyNames.ARCHER,
  UNDEADARCHER: enemyNames.ARCHER,

  SHIELDBEARER: enemyNames.SHIELDBEARER,

  GRENADIER: enemyNames.GRENADIER,

  BOMBARDIER: enemyNames.BOMBARDIER,

  BAT: enemyNames.BAT,

  KAMIKAZE: enemyNames.KAMIKAZE,

  RUNNER: enemyNames.RUNNER,

  INQUISITOR: enemyNames.INQUISITOR,
  MAGE360: enemyNames.INQUISITOR,

  PROTECTOR: enemyNames.PROTECTOR,

  HAMMER: enemyNames.HAMMER,

  SWEEPER: enemyNames.SWEEPER,
  MINIMOTH: enemyNames.SWEEPER,

  BUZZCUTTER: enemyNames.BUZZCUTTER,

  PURULENTZOMBIESEWER: enemyNames.PURULENT_ZOMBIE_S,

  PURULENTZOMBIEGRAVEYARD: enemyNames.PURULENT_ZOMBIE_G,

  DISGUSTINGWORM: enemyNames.DISGUSTING_WORM,

  SCORPION: enemyNames.SCORPION,

  IMPALER: enemyNames.IMPALER,

  SEWERTENTACLE: enemyNames.SEWER_TTCL,
  SEWERTTCL: enemyNames.SEWER_TTCL,

  CATCHER: enemyNames.CATCHER,
  HOOKER: enemyNames.HOOKER,

  CLEAVER: enemyNames.CLEAVER,
  AXETHROWER: enemyNames.CLEAVER,

  PIRATECAPTAIN: enemyNames.PIRATE_CAPTAIN,
  PIRATE: enemyNames.PIRATE_CAPTAIN,

  KNIFETHROWER: enemyNames.KNIFE_THROWER,

  SLASHER: enemyNames.SLASHER,

  LACERATOR: enemyNames.LACERATOR,
  SPINNER: enemyNames.SPINNER,

  SHOCKER: enemyNames.SHOCKER,

  THORNY: enemyNames.THORNY,

  SPAWNER: enemyNames.SPAWNER,

  MASKER: enemyNames.MASKER,
  FOGGER: enemyNames.FOGGER,

  CASTER: enemyNames.CASTER,

  GOLEM: enemyNames.GOLEM,

  DARKTRACKER: enemyNames.DARK_TRACKER,
  NINJA: enemyNames.DARK_TRACKER,

  CANNIBAL: enemyNames.CANNIBAL,

  AUTOMATON: enemyNames.AUTOMATON,
  TIMEKEEPERBOT: enemyNames.AUTOMATON,

  LANCER: enemyNames.LANCER,

  GUARDIANKNIGHT: enemyNames.GUARDIAN_KNIGHT,

  ROYALGUARD: enemyNames.ROYAL_GUARD,
  FINGEROFTHEKING: enemyNames.ROYAL_GUARD,
  KINGSFINGER: enemyNames.ROYAL_GUARD,

  BOMBER: enemyNames.BOMBER,

  SLAMMER: enemyNames.SLAMMER,
  BIRD: enemyNames.SLAMMER,

  DEMON: enemyNames.DEMON,

  ARBITER: enemyNames.ARBITER,

  GROUNDSHAKER: enemyNames.GROUND_SHAKER,

  SKELETON: enemyNames.SKELETON,
  BIGBOOTS: enemyNames.SKELETON,

  RAMPAGER: enemyNames.RAMPAGER,

  FAILEDEXPERIMENT: enemyNames.FAILED_EXP,

  DEFENDER: enemyNames.DEFENDER,

  MAGISTRATE: enemyNames.MAGISTRATE,
  MAGISTRATEOFDEATH: enemyNames.MAGISTRATE,

  LIBRARIAN: enemyNames.LIBRARIAN,

  YEETER: enemyNames.YEETER,
  PITCHER: enemyNames.PITCHER,

  JERKSHROOM: enemyNames.JERKSHROOM,
  MUSHROOM: enemyNames.JERKSHROOM,

  BANISHED: enemyNames.JERKSHROOM,

  BLOWGUNNER: enemyNames.BLOWGUNNER,

  RAT: enemyNames.RAT,
  RANCIDRAT: enemyNames.RAT,

  OVENKNIGHT: enemyNames.OVEN_KNIGHT,
  GUARDIAN: enemyNames.OVEN_KNIGHT,
  SHIELDKNIGHT: enemyNames.OVEN_KNIGHT,
  ENFORCER: enemyNames.OVEN_KNIGHT,

  BLOBBY: enemyNames.BLOBBY,
  BLOB: enemyNames.BLOBBY,
  TOXICMIASMA: enemyNames.BLOBBY,

  CRAB: enemyNames.CRAB,
  SAMURAI: enemyNames.CRAB,
  WEIRDEDWARRIOR: enemyNames.CRAB,

  FATZOMBIE: enemyNames.FAT_ZOMBIE,
  CORPULENTZOMBIE: enemyNames.FAT_ZOMBIE,
  MUMMY: enemyNames.FAT_ZOMBIE,

  DUELIST: enemyNames.DUELIST,
};
