// No inputType so it doesn't show up in search
export default {
  CLASSIC: { INTERNAL_ID: "CLASSIC", NAME: "Classic" },
  GOLDEN: { INTERNAL_ID: "PrisonerGold", NAME: "Golden" },
  LEGENDARYWARRIOR: { INTERNAL_ID: "PrisonerSonGoku", NAME: "" },
  NINJA: { INTERNAL_ID: "PrisonerBlack", NAME: "" },
  GHOST: { INTERNAL_ID: "PrisonerGhost", NAME: "" },
  DONATELLO: { INTERNAL_ID: "PrisonerSewers", NAME: "" },
  FESTIVE: { INTERNAL_ID: "PrisonerSanta", NAME: "" },
  FISHERMAN: { INTERNAL_ID: "PrisonerStilt", NAME: "" },
  SKELETON: { INTERNAL_ID: "PrisonerSkeleton", NAME: "" },
  CARDUUS: { INTERNAL_ID: "PrisonerCarduus", NAME: "" },
  APHRODITE: { INTERNAL_ID: "PrisonerAphrodite", NAME: "" },
  SHAMAN: { INTERNAL_ID: "PrisonerShaman", NAME: "" },
  CLOUD: { INTERNAL_ID: "PrisonerCloud", NAME: "" },
  DRIFTER: { INTERNAL_ID: "PrisonerHyperlight", NAME: "" },
  ATHOUSANDANDONENIGHTS: { INTERNAL_ID: "PrisonerAladdin", NAME: "" },
  DICTATOR: { INTERNAL_ID: "PrisonerBison", NAME: "" },
  WARRIOR: { INTERNAL_ID: "PrisonerWarrior", NAME: "" },
  MAGE: { INTERNAL_ID: "PrisonerMage", NAME: "" },
  NEON: { INTERNAL_ID: "PrisonerNeon", NAME: "" },
  BOBBY: { INTERNAL_ID: "PrisonerBobby", NAME: "" },
  DEMON: { INTERNAL_ID: "PrisonerDemon", NAME: "" },
  ROBINHOOD: { INTERNAL_ID: "PrisonerSylvanian", NAME: "" },
  DESERTDWELLER: { INTERNAL_ID: "PrisonerSand", NAME: "" },
  GALAXY: { INTERNAL_ID: "PrisonerGOG", NAME: "" },
  BAGUETTE: { INTERNAL_ID: "PrisonerFrench", NAME: "" },
  FLYINGALCOHOLIC: { INTERNAL_ID: "PrisonerXmas", NAME: "" },
  GARDENERS: { INTERNAL_ID: "PrisonerGardener", NAME: "" },
  MUSHROOMBOIS: { INTERNAL_ID: "PrisonerFriendlyHardy", NAME: "" },
  MUSHROOMKING: { INTERNAL_ID: "PrisonerMushroom", NAME: "" },
  BANISHEDS: { INTERNAL_ID: "PrisonerFugitive", NAME: "" },
  BLOWGUNNERS: { INTERNAL_ID: "PrisonerBlowgunner", NAME: "" },
  TICKTRAINER: { INTERNAL_ID: "PrisonerTick", NAME: "" },
  ROYALGARDENERS: { INTERNAL_ID: "RoyalGardener", NAME: "" },
  RETRO: { INTERNAL_ID: "PrisonerRetro", NAME: "" },
  HEV: { INTERNAL_ID: "FreemanSkin", NAME: "" },
  KAMIKAZEE: { INTERNAL_ID: "PrisonerKamikazee", NAME: "" },
  ARBALESTERS: { INTERNAL_ID: "Prisoner", NAME: "" },
  BLADEMASTERS: { INTERNAL_ID: "Prisoner", NAME: "" },
  REVERSEBURGLARS: { INTERNAL_ID: "Prisoner", NAME: "" },
  WINTER: { INTERNAL_ID: "Prisoner", NAME: "" },
  LIZARD: { INTERNAL_ID: "Prisoner", NAME: "" },
  APOSTATE: { INTERNAL_ID: "Prisoner", NAME: "" },
  ALMOSTYOURSELF: { INTERNAL_ID: "Prisoner", NAME: "" },
  CULTIST: { INTERNAL_ID: "Prisoner", NAME: "" },
  ROCKY: { INTERNAL_ID: "Prisoner", NAME: "" },

  // ------------------------------- BOSSES --------------------------------- //
  CONCIERGE1: { INTERNAL_ID: "", NAME: "" },
  CONCIERGE2: { INTERNAL_ID: "", NAME: "" },
  CONCIERGE3: { INTERNAL_ID: "", NAME: "" },
  CONCIERGE4: { INTERNAL_ID: "", NAME: "" },
  CONCIERGE5: { INTERNAL_ID: "", NAME: "" },

  CONJ1: { INTERNAL_ID: "", NAME: "" },
  CONJ2: { INTERNAL_ID: "", NAME: "" },
  CONJ3: { INTERNAL_ID: "", NAME: "" },
  CONJ4: { INTERNAL_ID: "", NAME: "" },
  CONJ5: { INTERNAL_ID: "", NAME: "" },

  TICK1: { INTERNAL_ID: "", NAME: "" },
  TICK2: { INTERNAL_ID: "", NAME: "" },
  TICK3: { INTERNAL_ID: "", NAME: "" },
  TICK4: { INTERNAL_ID: "", NAME: "" },
  TICK5: { INTERNAL_ID: "", NAME: "" },

  TIMEKEEPER1: { INTERNAL_ID: "", NAME: "" },
  TIMEKEEPER2: { INTERNAL_ID: "", NAME: "" },
  TIMEKEEPER3: { INTERNAL_ID: "", NAME: "" },
  TIMEKEEPER4: { INTERNAL_ID: "", NAME: "" },
  TIMEKEEPER5: { INTERNAL_ID: "", NAME: "" },

  GIANT1: { INTERNAL_ID: "", NAME: "" },
  GIANT2: { INTERNAL_ID: "", NAME: "" },
  GIANT3: { INTERNAL_ID: "", NAME: "" },
  GIANT4: { INTERNAL_ID: "", NAME: "" },
  GIANT5: { INTERNAL_ID: "", NAME: "" },

  SCARECROW1: { INTERNAL_ID: "", NAME: "" },
  SCARECROW2: { INTERNAL_ID: "", NAME: "" },
  SCARECROW3: { INTERNAL_ID: "", NAME: "" },
  SCARECROW4: { INTERNAL_ID: "", NAME: "" },
  SCARECROW5: { INTERNAL_ID: "", NAME: "" },

  HOTK1: { INTERNAL_ID: "", NAME: "" },
  HOTK2: { INTERNAL_ID: "", NAME: "" },
  HOTK3: { INTERNAL_ID: "", NAME: "" },
  HOTK4: { INTERNAL_ID: "", NAME: "" },
  HOTK5: { INTERNAL_ID: "", NAME: "" },

  KING: { INTERNAL_ID: "", NAME: "" },
  WHITEKING: { INTERNAL_ID: "", NAME: "" },
  FALLENCOLLECTOR: { INTERNAL_ID: "", NAME: "" },
};
